name: Feature Selection

on:
  schedule:
    - cron: "0 11 * * *" # Runs daily at 4 PM PKT (UTC 11:00)
  workflow_dispatch: # Allows manual trigger

jobs:
  feature-selection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas "dvc[s3]"

      - name: Run feature selection script
        run: |
          Feature Selection/python feature_selection.py  

      - name: Initialize DVC (if not already initialized)
        run: dvc init --no-scm || echo "DVC already initialized"

      - name: Track feature_selection.csv with DVC
        run: |
          if [ ! -f "feature_selection.csv.dvc" ]; then
            dvc add feature_selection.csv
            git add feature_selection.csv.dvc
            git commit -m "Track feature_selection.csv with DVC [skip ci]" || echo "No DVC changes to commit"
          else
            dvc add feature_selection.csv
            git add feature_selection.csv.dvc
            git commit -m "Update feature_selection.csv with DVC [skip ci]" || echo "No DVC changes to commit"
          fi

      - name: Configure S3 remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Access Key ID: $AWS_ACCESS_KEY_ID"  # Debug
          echo "Secret Access Key: $AWS_SECRET_ACCESS_KEY"  # Debug
          dvc remote add -d myremote s3://your-bucket-name/path || echo "Remote already configured"
          dvc remote modify myremote endpointurl https://s3.amazonaws.com
          dvc remote modify myremote access_key_id "$AWS_ACCESS_KEY_ID"
          dvc remote modify myremote secret_access_key "$AWS_SECRET_ACCESS_KEY" || { echo "Failed to configure S3 remote"; exit 1; }

      - name: Push DVC cache to S3
        run: dvc push || { echo "DVC push failed"; exit 1; }

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feature_selection.csv.dvc
          git commit -m "Update feature_selection.csv with new data" || echo "No changes to commit"
          git push origin main  # Use default push with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}