name: Feature Selection

on:
  schedule:
    - cron: "0 11 * * *"  # Runs daily at 4 PM PKT (UTC 11:00)
  workflow_dispatch:       # Allows manual trigger

jobs:
  feature-selection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Install DVC with S3 support
        run: pip install dvc[s3]

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: echo "AWS credentials configured"

      - name: Pull latest feature_selection.csv from DVC remote
        run: dvc pull

      - name: Run feature selection script
        run: python "Feature Selection/feature_selection.py"

      - name: Track updated CSV with DVC
        run: dvc add feature_selection.csv

      - name: Commit DVC changes and push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feature_selection.csv.dvc .gitignore
          git commit -m "Update DVC-tracked feature_selection.csv [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Push data to S3 using DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: dvc push
